package frc.robot.Enums;

public enum AutoObjective {
    DRIVELINEAR, DRIVEROTATE, CARGOSEARCH,
    SHOOTHATCH, SHOOTCARGO, COLLECTCARGO, TILTCARGO, TILTHATCH, TILTTOPROCKET,
    ELEVATORFLOOR, ELEVATORREST, ELEVATORLOW, ELEVATORMID, ELEVATORHIGH,
    CLIMBEREXTENDFRONTLEGS,CLIMBEREXTENDBACKLEGS, CLIMBEREXTENDBOTH, CLIMBERDRIVE, RETRACTFRONTLEG, RETRACTBACKLEG;
}
