package frc.robot.Enums;

public enum AutoObjective {
    DRIVELINEAR, DRIVEROTATE,
    SHOOTHATCH, SHOOTCARGO, COLLECTCARGO,
    ELEVATORFLOOR, ELEVATORLOW, ELEVATORMID, ELEVATORHIGH,
    CLIMBEREXTENDFRONTLEGS,CLIMBEREXTENDBACKLEGS, CLIMBEREXTENDBOTH, CLIMBERDRIVE, RETRACTFRONTLEG, RETRACTBACKLEG;
}
